---
- name: Create ping exporter config
  become: true
  ansible.builtin.template:
    src: 'templates/ping_exporter_config.yml.j2'
    dest: "{{ ping_exporter__user_home }}/ping_exporter_config.yml"
    mode: 0640
    owner: "{{ ping_exporter__user }}"
    group: "{{ ping_exporter__group }}"
  notify:
    - "Systemctl restart ping_exporter.service"
