---
- name: Run optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Create User for ping exporter
  ansible.builtin.include_tasks: create_user.yml

- name: Get latest release and define version
  ansible.builtin.include_tasks: set_version.yml

- name: Install ping exporter
  ansible.builtin.include_tasks: install.yml

- name: Configurel ping exporter
  ansible.builtin.include_tasks: config.yml

- name: Start systemd unit
  ansible.builtin.include_tasks: systemd.yml
