---
- name: "Setup systemd service"
  become: true
  ansible.builtin.template:
    src: 'templates/ping_exporter.service.j2'
    dest: '/lib/systemd/system/ping_exporter.service'
    owner: root
    group: root
    mode: 0644
  notify:
    - "Systemctl restart ping_exporter.service"

- name: "Reload systemd"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  notify:
    - "Systemctl restart ping_exporter.service"

- name: Enable ping_exporter.service Service and make sure it started
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: 'ping_exporter.service'
    state: 'started'
